const Protocol = {
  SOCIAL_SERVER_PLAYER_CONNECTED: 0,
  SOCIAL_SERVER_PLAYER_DISCONNECTED: 1,
  SOCIAL_SERVER_CHAT_MESSAGE: 2,
  SOCIAL_SERVER_NOTIFY_PLAYER_ONLINE: 3,
  SOCIAL_SERVER_NOTIFY_PLAYER_OFFLINE: 4,
  MATCHMAKING_SERVER_PLAYER_CONNECTED: 5,
  MATCHMAKING_SERVER_PLAYER_DISCONNECTED: 6,
  MATCHMAKING_SERVER_FIND_GAME: 7,
  MATCHMAKING_SERVER_GAME_FOUND: 8,
  MATCHMAKING_SERVER_GAME_NOT_FOUND: 9
};

module.exports = Protocol;
